package com.B6.StockSystem.entities;

// Generated 2015-5-9 15:48:06 by Hibernate Tools 3.4.0.CR1

/**
 * Bankcard generated by hbm2java
 */
public class Bankcard implements java.io.Serializable {

	private Integer id;
	private User user;
	private String number;
	private Double balance;

	public Bankcard() {
	}

	public Bankcard(User user) {
		this.user = user;
	}

	public Bankcard(User user, String number, Double balance) {
		this.user = user;
		this.number = number;
		this.balance = balance;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public Double getBalance() {
		return this.balance;
	}

	public void setBalance(Double balance) {
		this.balance = balance;
	}

}
