package com.B6.StockSystem.entities;

// default package
// Generated 2015-5-1 21:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

	private int id;
	private User user;
	private Bbsblog bbsblog;
	private Date dateTime;
	private String content;
	private Set replies = new HashSet(0);

	public Comment() {
	}

	public Comment(int id, User user, Bbsblog bbsblog) {
		this.id = id;
		this.user = user;
		this.bbsblog = bbsblog;
	}

	public Comment(int id, User user, Bbsblog bbsblog, Date dateTime,
			String content, Set replies) {
		this.id = id;
		this.user = user;
		this.bbsblog = bbsblog;
		this.dateTime = dateTime;
		this.content = content;
		this.replies = replies;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Bbsblog getBbsblog() {
		return this.bbsblog;
	}

	public void setBbsblog(Bbsblog bbsblog) {
		this.bbsblog = bbsblog;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Set getReplies() {
		return this.replies;
	}

	public void setReplies(Set replies) {
		this.replies = replies;
	}

}
