package com.B6.StockSystem.entities;

// default package
// Generated 2015-5-1 21:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

	private int id;
	private Stock stock;
	private String name;
	private String tel;
	private String email;
	private String address;
	private String establisher;
	private Set stocks = new HashSet(0);

	public Company() {
	}

	public Company(int id, Stock stock) {
		this.id = id;
		this.stock = stock;
	}

	public Company(int id, Stock stock, String name, String tel, String email,
			String address, String establisher, Set stocks) {
		this.id = id;
		this.stock = stock;
		this.name = name;
		this.tel = tel;
		this.email = email;
		this.address = address;
		this.establisher = establisher;
		this.stocks = stocks;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getEstablisher() {
		return this.establisher;
	}

	public void setEstablisher(String establisher) {
		this.establisher = establisher;
	}

	public Set getStocks() {
		return this.stocks;
	}

	public void setStocks(Set stocks) {
		this.stocks = stocks;
	}

}
