package com.B6.StockSystem.entities;

// Generated 2015-5-9 15:48:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Expected generated by hbm2java
 */
public class Expected implements java.io.Serializable {

	private Integer id;
	private StockFocus stockFocus;
	private String price;
	private Date dateTime;
	private String operation;

	public Expected() {
	}

	public Expected(StockFocus stockFocus) {
		this.stockFocus = stockFocus;
	}

	public Expected(StockFocus stockFocus, String price, Date dateTime,
			String operation) {
		this.stockFocus = stockFocus;
		this.price = price;
		this.dateTime = dateTime;
		this.operation = operation;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public StockFocus getStockFocus() {
		return this.stockFocus;
	}

	public void setStockFocus(StockFocus stockFocus) {
		this.stockFocus = stockFocus;
	}

	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

}
