package com.B6.StockSystem.entities;

// Generated 2015-5-9 15:48:06 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Market generated by hbm2java
 */
public class Market implements java.io.Serializable {

	private Integer id;
	private String name;
	private Double curdot;
	private Double curprice;
	private Double rate;
	private Integer dealnumber;
	private Double turnover;
	private Set marketHasStocks = new HashSet(0);

	public Market() {
	}

	public Market(String name, Double curdot, Double curprice, Double rate,
			Integer dealnumber, Double turnover, Set marketHasStocks) {
		this.name = name;
		this.curdot = curdot;
		this.curprice = curprice;
		this.rate = rate;
		this.dealnumber = dealnumber;
		this.turnover = turnover;
		this.marketHasStocks = marketHasStocks;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getCurdot() {
		return this.curdot;
	}

	public void setCurdot(Double curdot) {
		this.curdot = curdot;
	}

	public Double getCurprice() {
		return this.curprice;
	}

	public void setCurprice(Double curprice) {
		this.curprice = curprice;
	}

	public Double getRate() {
		return this.rate;
	}

	public void setRate(Double rate) {
		this.rate = rate;
	}

	public Integer getDealnumber() {
		return this.dealnumber;
	}

	public void setDealnumber(Integer dealnumber) {
		this.dealnumber = dealnumber;
	}

	public Double getTurnover() {
		return this.turnover;
	}

	public void setTurnover(Double turnover) {
		this.turnover = turnover;
	}

	public Set getMarketHasStocks() {
		return this.marketHasStocks;
	}

	public void setMarketHasStocks(Set marketHasStocks) {
		this.marketHasStocks = marketHasStocks;
	}

}
