package com.B6.StockSystem.entities;

// Generated 2015-5-9 15:48:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * News generated by hbm2java
 */
public class News implements java.io.Serializable {

	private Integer id;
	private String title;
	private String author;
	private String content;
	private Date dateTime;

	public News() {
	}

	public News(String title, String author, String content, Date dateTime) {
		this.title = title;
		this.author = author;
		this.content = content;
		this.dateTime = dateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

}
