package com.B6.StockSystem.entities;

// default package
// Generated 2015-5-1 21:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Reply generated by hbm2java
 */
public class Reply implements java.io.Serializable {

	private int id;
	private User user;
	private Comment comment;
	private String content;
	private Date dateTime;

	public Reply() {
	}

	public Reply(int id, User user, Comment comment) {
		this.id = id;
		this.user = user;
		this.comment = comment;
	}

	public Reply(int id, User user, Comment comment, String content,
			Date dateTime) {
		this.id = id;
		this.user = user;
		this.comment = comment;
		this.content = content;
		this.dateTime = dateTime;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Comment getComment() {
		return this.comment;
	}

	public void setComment(Comment comment) {
		this.comment = comment;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

}
