package com.B6.StockSystem.entities;

// Generated 2015-5-9 15:48:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * StockHas generated by hbm2java
 */
public class StockHas implements java.io.Serializable {

	private Integer id;
	private User user;
	private Stock stock;
	private Double boughtInPrice;
	private Double amount;
	private Date dateTime;

	public StockHas() {
	}

	public StockHas(User user, Stock stock) {
		this.user = user;
		this.stock = stock;
	}

	public StockHas(User user, Stock stock, Double boughtInPrice,
			Double amount, Date dateTime) {
		this.user = user;
		this.stock = stock;
		this.boughtInPrice = boughtInPrice;
		this.amount = amount;
		this.dateTime = dateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	public Double getBoughtInPrice() {
		return this.boughtInPrice;
	}

	public void setBoughtInPrice(Double boughtInPrice) {
		this.boughtInPrice = boughtInPrice;
	}

	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

}
