package com.B6.StockSystem.entities;

// Generated 2015-5-9 15:48:06 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * StockFocus generated by hbm2java
 */
public class StockFocus implements java.io.Serializable {

	private Integer id;
	private User user;
	private Stock stock;
	private Set expecteds = new HashSet(0);

	public StockFocus() {
	}

	public StockFocus(User user, Stock stock) {
		this.user = user;
		this.stock = stock;
	}

	public StockFocus(User user, Stock stock, Set expecteds) {
		this.user = user;
		this.stock = stock;
		this.expecteds = expecteds;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	public Set getExpecteds() {
		return this.expecteds;
	}

	public void setExpecteds(Set expecteds) {
		this.expecteds = expecteds;
	}

}
