package com.B6.StockSystem.entities;

// default package
// Generated 2015-5-1 21:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * StockHistory generated by hbm2java
 */
public class StockHistory implements java.io.Serializable {

	private int id;
	private Stock stock;
	private Date date;
	private Double price;
	private Double scale;

	public StockHistory() {
	}

	public StockHistory(int id, Stock stock) {
		this.id = id;
		this.stock = stock;
	}

	public StockHistory(int id, Stock stock, Date date, Double price,
			Double scale) {
		this.id = id;
		this.stock = stock;
		this.date = date;
		this.price = price;
		this.scale = scale;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Double getScale() {
		return this.scale;
	}

	public void setScale(Double scale) {
		this.scale = scale;
	}

}
