package com.B6.StockSystem.entities;

// default package
// Generated 2015-5-1 21:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TradeHistory generated by hbm2java
 */
public class TradeHistory implements java.io.Serializable {

	private int id;
	private User user;
	private Stock stock;
	private Date dateTime;
	private Double price;
	private Boolean isBuy;

	public TradeHistory() {
	}

	public TradeHistory(int id, User user, Stock stock) {
		this.id = id;
		this.user = user;
		this.stock = stock;
	}

	public TradeHistory(int id, User user, Stock stock, Date dateTime,
			Double price, Boolean isBuy) {
		this.id = id;
		this.user = user;
		this.stock = stock;
		this.dateTime = dateTime;
		this.price = price;
		this.isBuy = isBuy;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Boolean getIsBuy() {
		return this.isBuy;
	}

	public void setIsBuy(Boolean isBuy) {
		this.isBuy = isBuy;
	}

}
