package com.B6.StockSystem.entities;

// Generated 2015-5-9 15:48:06 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String name;
	private String tel;
	private String email;
	private String address;
	private Boolean isAdministrator;
	private String nickname;
	private String password;
	private Set stockFocuses = new HashSet(0);
	private Set replies = new HashSet(0);
	private Set stockHases = new HashSet(0);
	private Set tradehistories = new HashSet(0);
	private Set bankcards = new HashSet(0);
	private Set bbsblogs = new HashSet(0);
	private Set comments = new HashSet(0);

	public User() {
	}

	public User(String name, String tel, String email, String address,
			Boolean isAdministrator, String nickname, String password,
			Set stockFocuses, Set replies, Set stockHases, Set tradehistories,
			Set bankcards, Set bbsblogs, Set comments) {
		this.name = name;
		this.tel = tel;
		this.email = email;
		this.address = address;
		this.isAdministrator = isAdministrator;
		this.nickname = nickname;
		this.password = password;
		this.stockFocuses = stockFocuses;
		this.replies = replies;
		this.stockHases = stockHases;
		this.tradehistories = tradehistories;
		this.bankcards = bankcards;
		this.bbsblogs = bbsblogs;
		this.comments = comments;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Boolean getIsAdministrator() {
		return this.isAdministrator;
	}

	public void setIsAdministrator(Boolean isAdministrator) {
		this.isAdministrator = isAdministrator;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getStockFocuses() {
		return this.stockFocuses;
	}

	public void setStockFocuses(Set stockFocuses) {
		this.stockFocuses = stockFocuses;
	}

	public Set getReplies() {
		return this.replies;
	}

	public void setReplies(Set replies) {
		this.replies = replies;
	}

	public Set getStockHases() {
		return this.stockHases;
	}

	public void setStockHases(Set stockHases) {
		this.stockHases = stockHases;
	}

	public Set getTradehistories() {
		return this.tradehistories;
	}

	public void setTradehistories(Set tradehistories) {
		this.tradehistories = tradehistories;
	}

	public Set getBankcards() {
		return this.bankcards;
	}

	public void setBankcards(Set bankcards) {
		this.bankcards = bankcards;
	}

	public Set getBbsblogs() {
		return this.bbsblogs;
	}

	public void setBbsblogs(Set bbsblogs) {
		this.bbsblogs = bbsblogs;
	}

	public Set getComments() {
		return this.comments;
	}

	public void setComments(Set comments) {
		this.comments = comments;
	}

}
